# Generated by Django 6.1.1 on 2026-09-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamo',
            table='prestamos',
        ),
        migrations.AlterModelTable(
            name='recurso',
            table='recursos',
        ),
    ]
